name: Playground Api Release Pipeline

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Zig
      run: sudo snap install zig --classic --beta
    - name: Install Cargo Lambda
      run: cargo install cargo-lambda
    - name: Build Release
      run: cargo lambda build --release --x86-64 --output-format zip
    - uses: actions/upload-artifact@v3
      with:
        name: bootstrap.zip
        path: target/lambda/playground-api/bootstrap.zip
  beta-deploy:
    environment: aws
    runs-on: ubuntu-latest
    needs: package
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
    - uses: actions/download-artifact@v3
      with:
        name: bootstrap.zip
        path: target/lambda/playground-api/bootstrap.zip
    - run: npm install cdk --global
    - run: npm --prefix dev/cdk install
    - run: npm --prefix dev/cdk run build
    - name: Deploy stack
      run: cdk deploy beta-playground-api-stack --app "node dev/cdk/dist/index" --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
  integration-test:
    environment: aws
    runs-on: ubuntu-latest
    needs: beta-deploy
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose -F integration
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2
  prod-deploy:
    environment: aws
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
    - uses: actions/download-artifact@v3
      with:
        name: bootstrap.zip
        path: target/lambda/playground-api/bootstrap.zip
    - run: npm install cdk --global
    - run: npm --prefix dev/cdk install
    - run: npm --prefix dev/cdk run build
    - name: Deploy stack
      run: cdk deploy prod-playground-api-stack --app "node dev/cdk/dist/index" --require-approval never
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1